#!/usr/bin/env python3
"""
Report Generator Utility
"""

import json
from datetime import datetime
from typing import List, Dict

class ReportGenerator:
    def __init__(self, target: str, scan_type: str):
        self.target = target
        self.scan_type = scan_type
        self.start_time = datetime.now()
        self.vulnerabilities = []
    
    def add_vulnerability(self, vuln: Dict):
        """Add vulnerability to report"""
        self.vulnerabilities.append(vuln)
    
    def generate_markdown(self) -> str:
        """Generate markdown report"""
        end_time = datetime.now()
        duration = (end_time - self.start_time).total_seconds()
        
        # Count by severity
        severity_counts = {
            "critical": 0,
            "high": 0,
            "medium": 0,
            "low": 0,
            "info": 0
        }
        
        for vuln in self.vulnerabilities:
            severity = vuln.get("severity", "info").lower()
            if severity in severity_counts:
                severity_counts[severity] += 1
        
        # Calculate risk score
        risk_score = (
            severity_counts["critical"] * 10 +
            severity_counts["high"] * 7 +
            severity_counts["medium"] * 4 +
            severity_counts["low"] * 2 +
            severity_counts["info"] * 1
        ) / 10
        risk_score = min(risk_score, 10.0)
        
        report = f"""# Security Assessment Report

## Executive Summary
- **Target**: {self.target}
- **Scan Type**: {self.scan_type}
- **Date**: {self.start_time.strftime('%Y-%m-%d %H:%M:%S')}
- **Duration**: {duration:.2f} seconds
- **Total Vulnerabilities**: {len(self.vulnerabilities)}
- **Risk Score**: {risk_score:.1f}/10

## Vulnerability Summary
- 🔴 Critical: {severity_counts['critical']}
- 🟣 High: {severity_counts['high']}
- 🟡 Medium: {severity_counts['medium']}
- 🔵 Low: {severity_counts['low']}
- ⚪ Info: {severity_counts['info']}

## Technical Findings

"""
        
        # Add vulnerabilities
        for i, vuln in enumerate(self.vulnerabilities, 1):
            severity = vuln.get("severity", "info").upper()
            location = vuln.get("location", "N/A")
            impact = vuln.get("impact", "N/A")
            remediation = vuln.get("remediation", "N/A")
            evidence = vuln.get("evidence", "N/A")
            
            report += f"""### {i}. {vuln.get('name', 'Unknown Vulnerability')}
- **Severity**: {severity}
- **Location**: {location}
- **Impact**: {impact}
- **Remediation**: {remediation}
- **Evidence**: 
```
{evidence}
```

"""
        
        report += f"""## Recommendations

1. **Immediate Actions**:
   - Address all Critical and High severity vulnerabilities
   - Implement security headers
   - Review authentication and authorization mechanisms

2. **Short-term Actions**:
   - Fix Medium severity issues
   - Conduct code review
   - Implement input validation

3. **Long-term Actions**:
   - Establish security testing in CI/CD
   - Regular penetration testing
   - Security awareness training

---
*Report generated by BreakingCID Platform*
*Timestamp: {end_time.strftime('%Y-%m-%d %H:%M:%S')}*
"""
        
        return report
    
    def generate_json(self) -> str:
        """Generate JSON report"""
        end_time = datetime.now()
        duration = (end_time - self.start_time).total_seconds()
        
        report = {
            "target": self.target,
            "scan_type": self.scan_type,
            "start_time": self.start_time.isoformat(),
            "end_time": end_time.isoformat(),
            "duration_seconds": duration,
            "total_vulnerabilities": len(self.vulnerabilities),
            "vulnerabilities": self.vulnerabilities
        }
        
        return json.dumps(report, indent=2)
    
    def save_report(self, output_path: str, format: str = "markdown"):
        """Save report to file"""
        if format == "markdown":
            content = self.generate_markdown()
        elif format == "json":
            content = self.generate_json()
        else:
            raise ValueError(f"Unsupported format: {format}")
        
        with open(output_path, 'w') as f:
            f.write(content)
        
        return output_path

if __name__ == "__main__":
    # Test
    report = ReportGenerator("https://example.com", "XSS Scanner")
    
    report.add_vulnerability({
        "name": "Reflected XSS",
        "severity": "high",
        "location": "/search?q=",
        "impact": "Attacker can execute arbitrary JavaScript",
        "remediation": "Implement proper output encoding",
        "evidence": "<script>alert(1)</script>"
    })
    
    report.add_vulnerability({
        "name": "Missing Security Headers",
        "severity": "medium",
        "location": "All pages",
        "impact": "Increased attack surface",
        "remediation": "Add CSP, X-Frame-Options, etc.",
        "evidence": "No security headers detected"
    })
    
    print(report.generate_markdown())
